### PR TITLE
Fix error for large matrix norm

### LINKED ISSUE #10: Error with trunc!
Hi,

I am running a Bayesian inference on an ODE model using Turing.jl. To speed up things, I represented the model as a linear system and expressed the coefficients in the form of a matrix to solve the system using matrix exponential (ExponentialAction.expv()). When I run the inference, I keep getting the error below (this is only the head of the error but I can try to share the rest if necessary). 

Any ideas on how to solve this!

Thank you.
Ahmed.

PS: the full model structure is also below. It is a PBPK model where I am modeling a drug's pharmacokinetics in patients. The drug is introduced via IV infusion so the model is set to calculate the state variables using the relation `u(t)=A^-1 * exp(A*t) * rate - A^-1 * rate`. Once infusion duration is over I switch to `u(t)=exp(A*t) * u0` The CLint parameter includes random effects relevant to interindividual variability. The function `PBPK()` would take in the parameter set and generate the full model coefficients matrix. I haven't attached the full function description but I can if necessary!

```
ERROR: InexactError: trunc(Int64, 1.0868108130524078e19)
Stacktrace:

trunc at [./float.jl]()

ceil at [./float.jl]()

parameters(t::Float64, A::Matrix{Float64}, n0::Int64, m_max::Int64, p_max::Int64, tol::Float64) at [/Users/ahmede/.julia/packages/ExponentialAction/GSSyv/src/parameters.jl]()

expv(t::Float64, A::Matrix{Float64}, B::Vector{Float64}; shift::Bool, tol::Float64) at [/Users/ahmede/.julia/packages/ExponentialAction/GSSyv/src/expv.jl]()

expv(t::Float64, A::Matrix{Float64}, B::Vector{Float64}) at [/Users/ahmede/.julia/packages/ExponentialAction/GSSyv/src/expv.jl]()
```

Full model structure:

```
@model function fitPBPK(data, nSubject, rates, times, durs, wts, VVBs, BP, starts, ends, ncmt) # data should be a Vector
    # priors
    σ ~ truncated(Cauchy(0, 0.5), 0.0, Inf) # residual error
    ĈLint ~ LogNormal(7.1,0.25)
    KbBR ~ LogNormal(1.1,0.25)
    KbMU ~ LogNormal(0.3,0.25)
    KbAD ~ LogNormal(2.0,0.25)
    KbBO ~ LogNormal(0.03, 0.25)
    KbRB ~ LogNormal(0.3, 0.25)
    ω ~ truncated(Cauchy(0, 0.5), 0.0, 1.0)
    ηᵢ ~ filldist(Normal(0.0, 1.0), nSubject)

    # individual params
    CLintᵢ = ĈLint .* exp.(ω .* ηᵢ)  # non-centered parameterization

    # solve
    tmp_rate = zeros(ncmt)
    #ut = zeros(ncmt,length(data))
    predicted = []

    ps_tmp = [CLintᵢ[1], KbBR, KbMU, KbAD, KbBO, KbRB, wts[1]]
    K_tmp = PBPK(ps_tmp)
    #tmp_rate[15] = rates[1]
    #u0_eoi_tmp = inv(K_tmp)*exp(K_tmp*durs[1])*tmp_rate - inv(K_tmp)*tmp_rate
    u0_eoi_tmp = inv(K_tmp)*ExponentialAction.expv(durs[1], K_tmp, tmp_rate) - inv(K_tmp)*tmp_rate
    ut = zeros(Base.promote_eltype(times[1], K_tmp, u0_eoi_tmp), length(u0_eoi_tmp), length(data))

    for i in 1:nSubject
        tmp_rate[15] = rates[i]
        ps = [CLintᵢ[i], KbBR, KbMU, KbAD, KbBO, KbRB, wts[i]]
        K = PBPK(ps)
        u0_eoi = inv(K)*ExponentialAction.expv(durs[i], K, tmp_rate) - inv(K)*tmp_rate
        #u0_eoi = inv(K)*exp(K*durs[i])*tmp_rate - inv(K)*tmp_rate
        n = 1
        for j in starts[i]:ends[i]
            tmp_time = times[i][n]
            if tmp_time <= durs[i]
                ut[:,j] = inv(K)*ExponentialAction.expv(tmp_time, K, tmp_rate) - inv(K)*tmp_rate
                #ut[:,j] = inv(K)*ExponentialUtilities.exp_generic(K*tmp_time)*tmp_rate - inv(K)*tmp_rate
            else
                ut[:,j] = ExponentialAction.expv(tmp_time, K, u0_eoi)
                #ut[:,j] = ExponentialUtilities.exp_generic(K*tmp_time)*u0_eoi
            end 
            n = n + 1
        end
        tmp_sol = ut[15,starts[i]:ends[i]] ./ (VVBs[i]*BP/1000.0)
        append!(predicted, tmp_sol)
    end

    # likelihood
    for i = 1:length(predicted)
        data[i] ~ LogNormal(log.(predicted[i]), σ)
    end
end
```

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #10

@aelmokadem can you confirm this fixes your issue?

### CODE REVIEW

**Comment by aelmokadem** [comment]
Is what I need to do to get that fix os to update the package and it would pull it?

**Comment by sethaxen** [comment]
> Is what I need to do to get that fix os to update the package and it would pull it?

After an hour or so when v0.1.4 is released, yes, that would work. Or you could do
```julia
] add ExponentialActions#main
```
which would pull in the fix from the main branch.

**Comment by aelmokadem** [comment]
Yup.. that indeed fixed the issue. Thank you so much @sethaxen  :)

**Comment by sethaxen** [comment]
Glad to hear it! And, you're welcome!

**Pull request merged**
